### ISSUE TITLE
Codepen links on demo examples do not work

### ISSUE THREAD

**Issue by florisb** [angular/code.material.angularjs.org#3]
The links to angular material css & js are wrong. They are linked to localhost instead of an online location.

Changing http://localhost:8080/angular-material.js to https://material.angularjs.org/latest/angular-material.js fixes it. 

I read in this in the source:

    // The following URL's need to use `localhost` as these values get replaced during release
    var CORE_JS  = 'http://localhost:8080/angular-material.js';
    var CORE_CSS = 'http://localhost:8080/angular-material.css';
    var DOC_CSS  = 'http://localhost:8080/docs.css';  

But that seems to be broken.

**Comment by ThomasBurleson** [comment]
Please do not post issues on the docs repository.
